### PR TITLE
Restructure `InternalSaveChangesDsl`

### LINKED ISSUE #1736: Can't implement InternalSaveChangesDsl for another backend
### Versions

- **Rust:** nightly-2018-03-07-x86_64-unknown-linux-gnu
- **Diesel:** 1.2.2
- **Database:** Oracle 12g
- **Operating System** Ubuntu 18.04

## Problem Description
I am trying to get another backend for diesel working. Namely oracle/oci. Therefore I need to implement e.g. ```InternalSaveChangesDsl```. Since all oracle/oci related code is currently outside of diesel, it is impossible to implement this. Please note that I made `save_changes_dsl` public.

### What is the actual output?
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for a type parameter
  --> src/oracle/query_dsl/save_changes_dsl.rs:15:1
   |
15 | / impl<T, U> InternalSaveChangesDsl<OciConnection, U> for T
16 | |     where
17 | |         T: Copy + Identifiable,
18 | |         T: AsChangeset<Target = <T as HasTable>::Table> + IntoUpdateTarget,
...  |
26 | |     }
27 | | }
   | |_^
```
### Steps to reproduce
There is some code at https://github.com/GiGainfosystems/diesel-oci/tree/feature/save_changes_dsl available. I also had to change some diesel code: https://github.com/GiGainfosystems/diesel/tree/feature/save_changes_dsl
Within `diesel/diesel_tests` I run
```
cargo +nightly test --features oracle
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### PR DESCRIPTION
**Pull request by weiznich**
This allows this trait to be implemented outside of diesel.
Also reexport this trait as hidden api. (It is only usfull if someone
tries to implement a additional backend)

This is not a breaking change because `InternalSaveChangesDsl` was an internal api.

Fix #1736

### CODE REVIEW

File: diesel/src/query_dsl/save_changes_dsl.rs [hunk 1]
```diff
@@ -114,13 +115,13 @@ where
 /// #     Ok(())
 /// # }
 /// ```
-pub trait SaveChangesDsl<Conn> {
+pub trait SaveChangesDsl<Conn>: Sized {
```
Comment (sgrif) [inline diesel/src/query_dsl/save_changes_dsl.rs]: The `Sized` bound should be on the method, not the trait. Putting it here is technically a breaking change.

File: diesel/src/query_dsl/mod.rs [hunk 2]
```diff
@@ -49,6 +49,8 @@ pub use self::load_dsl::LoadQuery;
 pub use self::group_by_dsl::GroupByDsl;
 pub use self::join_dsl::{InternalJoinDsl, JoinOnDsl, JoinWithImplicitOnClause};
 pub use self::save_changes_dsl::SaveChangesDsl;
+#[doc(hidden)]
+pub use self::save_changes_dsl::InternalSaveChangesDsl;
```
Comment (sgrif) [inline diesel/src/query_dsl/mod.rs]: Why do we need this?

Comment (weiznich) [reply diesel/src/query_dsl/mod.rs]: Because otherwise it is not possible to implement it outside of diesel. (Because otherwise it is private)

File: diesel/src/query_dsl/save_changes_dsl.rs [hunk 3]
```diff
@@ -7,26 +7,33 @@ use query_dsl::{LoadQuery, RunQueryDsl};
...
-pub trait InternalSaveChangesDsl<T, U> {
-    fn internal_save_changes(&self, changeset: T) -> QueryResult<U>;
+/// A trait defining how to update a record and fetch the updated entry
+/// on a certain backend.
+///
+/// The only case where it is required to work with this trait is while
+/// implementing a new connection type.
+/// Otherwise use [`SaveChangesDsl`](trait.SaveChangesDsl.html)
+pub trait UpdateAndFetchResults<T, U>: Connection {
+    /// See the traits documentation.
```
Comment (Mingun) [inline diesel/src/query_dsl/save_changes_dsl.rs]: I think, you can describe, than usually there will be changeset and what are `T` and `U`

File: diesel/src/query_dsl/save_changes_dsl.rs [hunk 4]
```diff
@@ -7,62 +7,70 @@ use query_dsl::{LoadQuery, RunQueryDsl};
...
 
-pub trait InternalSaveChangesDsl<Conn, T>: Sized {
-    fn internal_save_changes(self, connection: &Conn) -> QueryResult<T>;
+/// A trait defining how to update a record and fetch the updated entry
+/// on a certain backend.
+///
+/// The only case where it is required to work with this trait is while
+/// implementing a new connection type.
+/// Otherwise use [`SaveChangesDsl`](trait.SaveChangesDsl.html)
+pub trait UpdateAndFetchResults<T, U>: Connection {
```
Comment (sgrif) [inline diesel/src/query_dsl/save_changes_dsl.rs]: Can we give these more descriptive names? e.g. `Changes` and `Output`?
