### PR TITLE
Generate `InstrumentationEvent::BeginTransaction` for custom transaction SQL

### LINKED ISSUE #4392: Missing transaction instrumentation in `AnsiTransactionManager`
### Versions

- **Rust:** 1.83.0
- **Diesel:** 2.2.6
- **Database:** SQLite
- **Operating System** Linux

### Feature Flags

- **diesel:** `r2d2`, `returning_clauses_for_sqlite_3_35`, `sqlite`, `uuid`

## Problem Description

The following problem happens with `SqliteConnection`'s methods `immediate_transaction()` and `exclusive_transaction()`. Under the hood, these use `AnsiTransactionManager::begin_transaction_sql()` instead of the usual `begin_transaction()` (implemented for trait `TransactionManager`).

The latter method's implementation generates instrumentation events of type `InstrumentationEvent::BeginTransaction`:

https://github.com/diesel-rs/diesel/blob/b705023d85e6ef76292a427aa70f21c28a5902ff/diesel/src/connection/transaction_manager.rs#L337-L359

The former, however, is not generating these events:

https://github.com/diesel-rs/diesel/blob/b705023d85e6ef76292a427aa70f21c28a5902ff/diesel/src/connection/transaction_manager.rs#L314-L329

This causes custom instrumentation to no longer uphold the invariant that every `BeginTransaction` is followed by exactly one of either `RollbackTransaction` or `CommitTransaction`.

### What are you trying to accomplish?

Trace ongoing transactions using custom instrumentation, including `IMMEDIATE` and `EXCLUSIVE` transactions.

### What is the expected output?

Using `SqliteConnection::immediate_transaction()` or `exclusive_transaction()` over the regular `transaction()` should generate the same instrumentation events. In particular, starting transactions with these two methods should generate a `BeginTransaction` event.

### What is the actual output?

Transactions started with `SqliteConnection::immediate_transaction()` or `exclusive_transaction()` do not generate the expected instrumentation event `BeginTransaction`.

### Are you seeing any additional errors?

No.

### Steps to reproduce

See above. The problem is independent of any actual database structure or queries inside the transcation.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

### PR DESCRIPTION
**Pull request by sgoll**
Fixes #4392

### CODE REVIEW

**Comment by weiznich** [comment]
Thanks for opening this PR, seems like this was just missed while implementing that feature. 

> Please note that I was unsure which branch to base this pull request on. I picked 2.2.x because that seems to include the latest release. However, I can easily rebase my changes on top of master if necessary.

PR's should target the master branch by default as that's where the development is happening. If something is an important fix we might backport is later. That could be the case here.

File: diesel/src/connection/transaction_manager.rs [hunk 1]
```diff
@@ -316,15 +316,22 @@ impl AnsiTransactionManager {
...
-            Some(_depth) => Err(Error::AlreadyInTransaction),
+        if let Some(_depth) = state.transaction_depth() {
+            return Err(Error::AlreadyInTransaction);
         }
+        let instrumentation_depth = NonZeroU32::new(1);
+        // Keep remainder of this method in sync with `begin_transaction()`.
+
+        conn.instrumentation().on_connection_event(
+            super::instrumentation::InstrumentationEvent::BeginTransaction {
+                depth: instrumentation_depth.expect("Transaction depth is too large"),
```
Comment (weiznich) [inline diesel/src/connection/transaction_manager.rs:327]:
```suggestion
                depth: instrumentation_depth.expect("We know that 1 is not zero"),
```

**Review by weiznich — APPROVED** [review]
