### PR TITLE
fix: connect to template1 when database is postgres

### LINKED ISSUE #4275: `diesel database reset` errors with `Failed to execute a database query`
### Versions

- **Rust:** `rustc 1.83.0-nightly (506f22b46 2024-09-19)`
- **Diesel:** `2.2.4`
- **Database:** `postgres`
- **Operating System:** Linux

### Feature Flags

- **diesel:** `["postgres"]`

### What are you trying to accomplish?

Run `diesel database reset`.

### What is the expected output?

Database is successfully reset.

### What is the actual output?

```
Dropping database: postgres
Failed to execute a database query: cannot drop the currently open database
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

`.env`
```bash
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
```

`diesel.toml`
```toml
[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "migrations"
```

I only have one migration file:

`up.sql`
```sql
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
);
```
`down.sql`
```sql
DROP TABLE IF EXISTS users;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

### PR DESCRIPTION
**Pull request by zaira-bibi**
Closes #4275.

**Description**
Diesel explicitly connected to `postgres` to drop any other database, which posed issues when `postgres` itself was to be dropped. 

**Changes**
Added a check for the current database, and connect to `template1` for the case when current database is `postgres`.

### CODE REVIEW

File: diesel_cli/src/database.rs [hunk 1]
```diff
@@ -429,6 +429,11 @@ fn change_database_of_url(
         .last()
         .expect("The database url has at least one path segment")
         .to_owned();
+
+    if database.eq("postgres") {
```
Comment (Ten0) [inline diesel_cli/src/database.rs:433]: I've read the issue and I understand it may be sensible to do this specifically when we are trying to drop a database.
It also sounds likely that at the moment this is the only place at which this function is called.
However the naming of this function  `fn change_database_of_url(` would not let any future code author expect this behavior, so it's likely to introduce a bug.
I think it would be best to put this logic where the function is called, that is in a place where the current code path is about removing the database.

Comment (zaira-bibi) [reply diesel_cli/src/database.rs:433]: Thanks for the review! I get what you mean, will push a commit with the required change.

**Review by weiznich — APPROVED** [review]
Thanks for fixing this :heart:
