### PR TITLE
Display the correct migration order in `diesel migration list`

### LINKED ISSUE #1500: diesel lists migrations in wrong chronological order
Diesel lists migrations in wrong chronological order after the date format changed.
It lists `2017-11-23-064836` before `20170505070309`:
http://pastebin.centos.org/504376/64198071/

### PR DESCRIPTION
**Pull request by sgrif**
The old code was incorrectly assuming that the migration version was
equal to the file name, which caused issues on projects that have
migrations using the old timestamp format. This continues to display the
actual file name, but sorts on migration version instead.

Fixes #1500

### CODE REVIEW

File: diesel_cli/src/main.rs [hunk 1]
```diff
@@ -77,33 +77,22 @@ fn run_migration_command(matches: &ArgMatches) {
...
-
-            sorted.sort();
+            migrations.sort_by_key(|&(ref m, _)| m.version().to_string());
 
             println!("Migrations:");
-            for (name, applied) in sorted {
+            for (migration, applied) in migrations {
+                let name = migration
+                    .file_path()
+                    .unwrap()
```
Comment (killercup) [inline diesel_cli/src/main.rs]: keep the nicer errors?

Comment (sgrif) [reply diesel_cli/src/main.rs]: Migrations that came from a `_in_directory` function always have a file path.
