### PR TITLE
Fix transactions not closing properly when failing on commit

### LINKED ISSUE #2346: Transaction does not close properly when failing on commit
### Versions

- **Rust:** latest stable
- **Diesel:** master
- **Database:** postgres
- **Operating System** linux

### Feature Flags

- **diesel:** postgres

## Problem Description
Connection gets released to the connection pool with transaction not being closed.
Then triggering "AlreadyInTransaction: Cannot perform this operation while a transaction is open" errors.

### What are you trying to accomplish?
Serializable transaction fails on transaction commit:
https://github.com/diesel-rs/diesel/blob/5369a7a3d13b1323fcac9acf9d13256f19a970a0/diesel/src/pg/transaction.rs#L276
"DatabaseError: could not serialize access due to read/write dependencies among transactions"
Connection is released to the pool (r2d2) and should be usable again.

### What is the expected output?
Next requests successfully start their own transaction.

### What is the actual output?
AlreadyInTransaction: Cannot perform this operation while a transaction is open

## Related issues
https://github.com/diesel-rs/diesel/issues/2123
In my case, transactions are not nested but I suspect this is the same issue.

## Solving
I suspect catching the `DatabaseError` on `commit_transaction` and calling `rollback_transaction` would solve this issue.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### PR DESCRIPTION
**Pull request by Ten0**
Resolves #2346

Connection could be made available again with a still-open transaction due to transaction commit fail (typically `SerializationFailure` or `ReadOnlyTransaction`).

This eventually triggered "AlreadyInTransaction: Cannot perform this operation while a transaction is open" errors in unrelated places.

This commit fixes this issue by catching `SerializationFailure` or `ReadOnlyTransaction` on commit and attempting a rollback.

### CODE REVIEW

File: diesel/src/connection/mod.rs [hunk 1]
```diff
@@ -95,10 +99,19 @@ pub trait Connection: SimpleConnection + Sized + Send {
         let transaction_manager = self.transaction_manager();
         transaction_manager.begin_transaction(self)?;
         match f() {
-            Ok(value) => {
-                transaction_manager.commit_transaction(self)?;
-                Ok(value)
-            }
+            Ok(value) => match transaction_manager.commit_transaction(self) {
```
Comment (weiznich) [inline diesel/src/connection/mod.rs:102]: Is there any specific reason to duplicate the error handling code here and in the postgres specific transaction implementation instead of handling it directly inside of `AnsiTransactionManager::commit_transaction`?

Comment (Ten0) [reply diesel/src/connection/mod.rs]: No you're right that was a mistake

**Comment by Ten0** [comment]
Do you think we should only use it on `COMMIT` and not on savepoints?

File: diesel/src/connection/transaction_manager.rs [hunk 2]
```diff
@@ -110,12 +110,21 @@ where
...
+    /// `ReadOnlyTransaction` rollback will be attempted. If it succeeds,
+    /// original error will be returned. If it fails, rollback error will be returned.
     fn commit_transaction(&self, conn: &Conn) -> QueryResult<()> {
         let transaction_depth = self.transaction_depth.get();
         self.change_transaction_depth(
             -1,
             if transaction_depth <= 1 {
-                conn.batch_execute("COMMIT")
+                conn.batch_execute("COMMIT").or_else(|err| match err {
+                    Error::DatabaseError(DatabaseErrorKind::SerializationFailure, _)
```
Comment (weiznich) [inline diesel/src/connection/transaction_manager.rs:122]: Maybe add a small note here why we have choosen to only handle those two error kinds? It should probably also state that it is fine to add other cases if it turns out to be a problem later.

File: diesel/src/connection/mod.rs [hunk 3]
```diff
@@ -45,6 +45,10 @@ pub trait Connection: SimpleConnection + Sized + Send {
     /// If there is already an open transaction,
     /// savepoints will be used instead.
     ///
+    /// If the transaction fails to commit due to a `SerializationFailure` or a
+    /// `ReadOnlyTransaction` rollback will be attempted. If it succeeds,
+    /// original error will be returned. If it fails, rollback error will be returned.
+    ///
```
Comment (weiznich) [inline diesel/src/connection/mod.rs:51]: Just some small wording improvements. I think they apply in the other comments too

```suggestion
    /// If the transaction fails to commit due to a `SerializationFailure` or a
    /// `ReadOnlyTransaction` a rollback will be attempted. If the rollback succeeds,
    /// the original error will be returned, otherwise the error generated by the rollback
    /// will be returned. In the second case the connection should be considered broken 
    /// as it contains a uncommitted unabortable open transaction.
```

File: diesel/src/connection/transaction_manager.rs (hunk 2 above)
Comment (Ten0) [reply diesel/src/connection/transaction_manager.rs]: done
