### PR TITLE
Fix documentation for importing any and all in pg

### LINKED ISSUE #2447: Documentation import incorrect `diesel::expression`
On the page: https://docs.rs/diesel/1.4.5/diesel/pg/expression/dsl/fn.any.html
It notes: 
> You can import it specifically from `diesel::expression::any`, or glob import `diesel::dsl::*`

I tried using the `diesel::expression::any` but this does not exist.
```
error[E0432]: unresolved import `diesel::expression::any`
 --> main.rs:8:5
  |
8 | use diesel::expression::any;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `any` in `expression`

error: aborting due to previous error
```
`use diesel::pg::expression::dsl::any;` does work.

So maybe the documentation has to be updated here.

### PR DESCRIPTION
**Pull request by ropottnik**
@weiznich I have now updated the documentations of importing `any` and `all` from `diesel/src/pg/expression/array_comparison.rs`. I wrote it as @ralpha suggested in the issue description. 

However, wouldn't it make more sense to offer `diesel::dsl::any` for the specific import? I'm asking because the original import documentation seemed unaware of `pg` as specific db backend. 

closes #2447

### CODE REVIEW

File: diesel/src/pg/expression/array_comparison.rs [hunk 1]
```diff
@@ -8,7 +8,7 @@ use crate::sql_types::Array;
 /// Creates a PostgreSQL `ANY` expression.
 ///
 /// As with most bare functions, this is not exported by default. You can import
-/// it specifically from `diesel::expression::any`, or glob import
+/// it specifically from `diesel::pg::expression::dsl::any`, or glob import
 /// `diesel::dsl::*`
```
Comment (JohnTitor) [inline diesel/src/pg/expression/array_comparison.rs:12]: nit:

```suggestion
/// `diesel::dsl::*`.
```

**Comment by weiznich** [comment]
@ropottnik Thanks for working on this :+1:

> However, wouldn't it make more sense to offer `diesel::dsl::any` for the specific import?

Yes, that would make more sense in my opinion. (I will add this as suggestions).

> I'm asking because the original import documentation seemed unaware of pg as specific db backend.

It is quite likely that this documentation was written back then when diesel only supported postgres and didn't change since then.

File: diesel/src/pg/expression/array_comparison.rs [hunk 2]
```diff
@@ -8,8 +8,8 @@ use crate::sql_types::Array;
 /// Creates a PostgreSQL `ANY` expression.
 ///
 /// As with most bare functions, this is not exported by default. You can import
-/// it specifically from `diesel::expression::any`, or glob import
-/// `diesel::dsl::*`
+/// it specifically from `diesel::pg::expression::dsl::any`, or glob import
+/// `diesel::dsl::*`.
```
Comment (weiznich) [inline diesel/src/pg/expression/array_comparison.rs:12]:
```suggestion
/// `diesel::dsl::any`.
```

File: diesel/src/pg/expression/array_comparison.rs [hunk 3]
```diff
@@ -37,7 +37,8 @@ where
 /// Creates a PostgreSQL `ALL` expression.
 ///
 /// As with most bare functions, this is not exported by default. You can import
-/// it specifically as `diesel::dsl::all`.
+/// it specifically as `diesel::pg::expression::dsl::all`, or glob import
+/// `diesel::dsl::*`.
```
Comment (weiznich) [inline diesel/src/pg/expression/array_comparison.rs:41]:
```suggestion
/// `diesel::dsl::all`.
```
