### PR TITLE
Fix/remove mem uninitialized

### LINKED ISSUE #2136: Remove cyclomatic-complexity-threshold from clippy.toml
### Versions

- **Rust:** 1.36
- **Diesel:**  1.4.2 patched to github master
- **Database:** sqlite3
- **Operating System** Linux 4.15

### Feature Flags

- **diesel:** sqlite

## Problem Description
When running `cargo clippy` on my project that depends on diesel the following error is reported, and clippy build aborts:
```
    Checking diesel v1.4.2 (https://github.com/diesel-rs/diesel#0b6c59e3)
error: error reading Clippy's configuration file `/home/rui/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/0b6c59e/clippy.toml`: found deprecated field `cyclomatic-complexity-threshold`. Please use `cognitive-complexity-threshold` instead.
```

### What are you trying to accomplish?
Run clippy

### What is the expected output?
`Finished dev [unoptimized + debuginfo] target(s) in 20.88s`

### What is the actual output?
See above

### Are you seeing any additional errors?
No

### Steps to reproduce
Run `cargo clippy`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

I replaced `cyclomatic-complexity-threshold` with `cognitive-complexity-threshold` in clippy.toml, and `cargo clippy` now builds.

### PR DESCRIPTION
**Pull request by weiznich**
Follow up to #2117 

Closes #2089
Closes #2136

### CODE REVIEW

File: diesel/src/serialize.rs [hunk 1]
```diff
@@ -76,7 +76,7 @@ impl<DB: TypeMetadata> Output<'static, Vec<u8>, DB> {
     /// Unsafe to use for testing types which perform dynamic metadata lookup.
     pub fn test() -> Self {
         use std::mem;
-        #[allow(clippy::invalid_ref)]
+        #[allow(clippy::invalid_ref, deprecated)]
```
Comment (JohnTitor) [inline diesel/src/serialize.rs]: Why do we allow this?

Comment (weiznich) [reply diesel/src/serialize.rs]: The alternative for the line below would be `Self::new(Vec::new(), unsafe { mem::MaybeUninit::uninit().assume_init() })` which would basically be also UB.
Therefore I think it is not worth changing it. 
(cc @diesel-rs/core just in case)

Comment (JohnTitor) [reply diesel/src/serialize.rs]: Ah okay, I got it. Could we add a comment about it?

Comment (weiznich) [reply diesel/src/serialize.rs]: A comment for what exactly? There is already a comment describing what this function tries to achieve.

Comment (JohnTitor) [reply diesel/src/serialize.rs]: I mean it's reasonable to leave a comment on why we use the deprecated method, what about?
